version: '3'
services:
    web:
        build: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
            - ./logs:/var/logs/nginx
        depends_on:
            - php-fpm
        links:
            - php-fpm
    php-fpm:
        build: php-fpm
        volumes:
            - ./www:/var/www